version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paymentapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_FLYWAY_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=secret
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      testenv: {}

  postgres:
    image: postgres:14-alpine
    container_name: posgresdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration/V1__init.sql:/docker-entrypoint-initdb.d/V1__init.sql
    networks:
      testenv: {}

networks:
  testenv:
    external: true
    name: testenv

volumes:
  postgres-data: